plugins:
  akismet_enabled:
    default: false
  akismet_api_key:
    default: ''
    shadowed_by_global: true
  akismet_transmit_email:
    default: true
  skip_akismet_trust_level:
    default: 2
    enum: 'TrustLevelSetting'
